---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: golang:1.20-alpine
    resource_class: small
    steps:
    - checkout
    - run:
        name: install prereqs
        command: apk add --no-cache --update build-base
    - run:
        name: build
        command: make build

workflows:
  execute_tests:
    jobs:
    - test
