---
resources:
- name: vault_resource
  type: git
  icon: github
  source:
    uri: https://github.com/mitodl/concourse-vault-resource
    branch: master
    paths:
    - concourse
    - vault
    - cmd
    - go.mod
    - Dockerfile

- name: concourse-vault-resource
  type: registry-image
  icon: docker
  source:
    tag: latest
    repository: mitodl/concourse-vault-resource
    username: ((dockerhub.username))
    password: ((dockerhub.password))

jobs:
- name: build-and-publish-image
  public: true
  plan:
  - get: vault_resource
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: vault_resource
      outputs:
      - name: image
      run:
        path: build
      params:
        CONTEXT: vault_resource
  - put: concourse-vault-resource
    params:
      image: image/image.tar
      additional_tags: vault_resource/.git/ref
