---
name: build

on:
  push:
    branches: [main]
    paths:
    - '**.go'
    - 'go.mod'
  pull_request:
    branches: [main]
    paths:
    - '**.go'
    - 'go.mod'

jobs:
  go-build:
    runs-on: ubuntu-22.04
    container: golang:1.19-alpine
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install prereqs
      run: apk add --no-cache --update build-base
    - name: build
      run: make build
